#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using ContextApi.Model;

namespace ContextApi.Model	
{
	public partial class DocumentMetadata
	{
		private string _title;
		public virtual string Title
		{
			get
			{
				return this._title;
			}
			set
			{
				this._title = value;
			}
		}
		
		private string _lastModified;
		public virtual string LastModified
		{
			get
			{
				return this._lastModified;
			}
			set
			{
				this._lastModified = value;
			}
		}
		
		private int _documentMetadataId;
		public virtual int DocumentMetadataId
		{
			get
			{
				return this._documentMetadataId;
			}
			set
			{
				this._documentMetadataId = value;
			}
		}
		
		private DateTime? _created;
		public virtual DateTime? Created
		{
			get
			{
				return this._created;
			}
			set
			{
				this._created = value;
			}
		}
		
		private string _author;
		public virtual string Author
		{
			get
			{
				return this._author;
			}
			set
			{
				this._author = value;
			}
		}
		
		private string _category;
		public virtual string Category
		{
			get
			{
				return this._category;
			}
			set
			{
				this._category = value;
			}
		}
		
		private double? _size;
		public virtual double? Size
		{
			get
			{
				return this._size;
			}
			set
			{
				this._size = value;
			}
		}
		
		private string _tag;
		public virtual string Tag
		{
			get
			{
				return this._tag;
			}
			set
			{
				this._tag = value;
			}
		}
		
		private IList<Project> _projects = new List<Project>();
		public virtual IList<Project> Projects
		{
			get
			{
				return this._projects;
			}
		}
		
		private Document _document;
		public virtual Document Document
		{
			get
			{
				return this._document;
			}
			set
			{
				this._document = value;
			}
		}
		
	}
}
#pragma warning restore 1591
