#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using ContextApi.Model;

namespace ContextApi.Model	
{
	public partial class Employee
	{
		private string _title;
		public virtual string Title
		{
			get
			{
				return this._title;
			}
			set
			{
				this._title = value;
			}
		}
		
		private int? _projectId;
		public virtual int? ProjectId
		{
			get
			{
				return this._projectId;
			}
			set
			{
				this._projectId = value;
			}
		}
		
		private string _lastName;
		public virtual string LastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				this._lastName = value;
			}
		}
		
		private string _firstName;
		public virtual string FirstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				this._firstName = value;
			}
		}
		
		private int _employeeId;
		public virtual int EmployeeId
		{
			get
			{
				return this._employeeId;
			}
			set
			{
				this._employeeId = value;
			}
		}
		
		private int? _reportToId;
		public virtual int? ReportToId
		{
			get
			{
				return this._reportToId;
			}
			set
			{
				this._reportToId = value;
			}
		}
		
		private string _department;
		public virtual string Department
		{
			get
			{
				return this._department;
			}
			set
			{
				this._department = value;
			}
		}
		
		private string _addres;
		public virtual string Addres
		{
			get
			{
				return this._addres;
			}
			set
			{
				this._addres = value;
			}
		}
		
		private Employee _employee1;
		public virtual Employee Supervisor
		{
			get
			{
				return this._employee1;
			}
			set
			{
				this._employee1 = value;
			}
		}
		
		private IList<TaskAssignment> _taskAssignments = new List<TaskAssignment>();
		public virtual IList<TaskAssignment> TaskAssignments
		{
			get
			{
				return this._taskAssignments;
			}
		}
		
		private IList<Employee> _employees1 = new List<Employee>();
		public virtual IList<Employee> Employees
		{
			get
			{
				return this._employees1;
			}
		}
		
		private IList<MonthlyReport> _monthlyReports = new List<MonthlyReport>();
		public virtual IList<MonthlyReport> MonthlyReports
		{
			get
			{
				return this._monthlyReports;
			}
		}
		
		private IList<DailyReport> _dailyReports = new List<DailyReport>();
		public virtual IList<DailyReport> DailyReports
		{
			get
			{
				return this._dailyReports;
			}
		}
		
		private IList<Project> _projects = new List<Project>();
		public virtual IList<Project> Projects
		{
			get
			{
				return this._projects;
			}
		}
		
	}
}
#pragma warning restore 1591
