#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using ContextApi.Model;

namespace ContextApi.Model	
{
	public partial class Task
	{
		private string _title;
		public virtual string Title
		{
			get
			{
				return this._title;
			}
			set
			{
				this._title = value;
			}
		}
		
		private int _taskId;
		public virtual int TaskId
		{
			get
			{
				return this._taskId;
			}
			set
			{
				this._taskId = value;
			}
		}
		
		private int _projectId;
		public virtual int ProjectId
		{
			get
			{
				return this._projectId;
			}
			set
			{
				this._projectId = value;
			}
		}
		
		private string _status;
		public virtual string Status
		{
			get
			{
				return this._status;
			}
			set
			{
				this._status = value;
			}
		}
		
		private int? _priority;
		public virtual int? Priority
		{
			get
			{
				return this._priority;
			}
			set
			{
				this._priority = value;
			}
		}
		
		private int? _percentCompleted;
		public virtual int? PercentCompleted
		{
			get
			{
				return this._percentCompleted;
			}
			set
			{
				this._percentCompleted = value;
			}
		}
		
		private Project _project;
		public virtual Project Project
		{
			get
			{
				return this._project;
			}
			set
			{
				this._project = value;
			}
		}
		
		private IList<TaskAssignment> _taskAssignments = new List<TaskAssignment>();
		public virtual IList<TaskAssignment> TaskAssignments
		{
			get
			{
				return this._taskAssignments;
			}
		}
		
	}
}
#pragma warning restore 1591
