#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using ContextApi.Model;

namespace ContextApi.Model	
{
	public partial class TaskAssignment
	{
		private int _taskAssignmentId;
		public virtual int TaskAssignmentId
		{
			get
			{
				return this._taskAssignmentId;
			}
			set
			{
				this._taskAssignmentId = value;
			}
		}
		
		private int _taskId;
		public virtual int TaskId
		{
			get
			{
				return this._taskId;
			}
			set
			{
				this._taskId = value;
			}
		}
		
		private int? _employeeId;
		public virtual int? EmployeeId
		{
			get
			{
				return this._employeeId;
			}
			set
			{
				this._employeeId = value;
			}
		}
		
		private int? _workingHours;
		public virtual int? WorkingHours
		{
			get
			{
				return this._workingHours;
			}
			set
			{
				this._workingHours = value;
			}
		}
		
		private Employee _employee;
		public virtual Employee Employee
		{
			get
			{
				return this._employee;
			}
			set
			{
				this._employee = value;
			}
		}
		
		private Task _task;
		public virtual Task Task
		{
			get
			{
				return this._task;
			}
			set
			{
				this._task = value;
			}
		}
		
	}
}
#pragma warning restore 1591
