'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by the ClassGenerator.ttinclude code generation file.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports Telerik.OpenAccess.Data.Common
Imports Telerik.OpenAccess.Metadata.Fluent
Imports Telerik.OpenAccess.Metadata.Fluent.Advanced
Imports ContextApi.Model

Namespace ContextApi.Model	
	Public Partial Class Bug
		Inherits Task
		Private _impact As Integer? 
		Public Overridable Property Impact As Integer?
			Get
		        Return Me._impact
			End Get
			Set(ByVal value As Integer?)
		        Me._impact = value
			End Set
		End Property
		
		Private _regression As Boolean 
		Public Overridable Property Regression As Boolean
			Get
		        Return Me._regression
			End Get
			Set(ByVal value As Boolean)
		        Me._regression = value
			End Set
		End Property
		
	End Class
End Namespace
