'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by the ClassGenerator.ttinclude code generation file.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports Telerik.OpenAccess.Data.Common
Imports Telerik.OpenAccess.Metadata.Fluent
Imports Telerik.OpenAccess.Metadata.Fluent.Advanced
Imports ContextApi.Model

Namespace ContextApi.Model	
	Public Partial Class DailyReport
		Inherits Report
		Private _dailyReportId As Integer 
		Public Overridable Property DailyReportId As Integer
			Get
		        Return Me._dailyReportId
			End Get
			Set(ByVal value As Integer)
		        Me._dailyReportId = value
			End Set
		End Property
		
		Private _startTime As Date? 
		Public Overridable Property StartTime As Date?
			Get
		        Return Me._startTime
			End Get
			Set(ByVal value As Date?)
		        Me._startTime = value
			End Set
		End Property
		
		Private _endTime As Date? 
		Public Overridable Property EndTime As Date?
			Get
		        Return Me._endTime
			End Get
			Set(ByVal value As Date?)
		        Me._endTime = value
			End Set
		End Property
		
		Private _employee As Employee 
		Public Overridable Property Employee As Employee
			Get
		        Return Me._employee
			End Get
			Set(ByVal value As Employee)
		        Me._employee = value
			End Set
		End Property
		
	End Class
End Namespace
