'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by the ClassGenerator.ttinclude code generation file.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports Telerik.OpenAccess.Data.Common
Imports Telerik.OpenAccess.Metadata.Fluent
Imports Telerik.OpenAccess.Metadata.Fluent.Advanced
Imports ContextApi.Model

Namespace ContextApi.Model	
	Public Partial Class DocumentMetadata
		Private _title As String 
		Public Overridable Property Title As String
			Get
		        Return Me._title
			End Get
			Set(ByVal value As String)
		        Me._title = value
			End Set
		End Property
		
		Private _lastModified As String 
		Public Overridable Property LastModified As String
			Get
		        Return Me._lastModified
			End Get
			Set(ByVal value As String)
		        Me._lastModified = value
			End Set
		End Property
		
		Private _documentMetadataId As Integer 
		Public Overridable Property DocumentMetadataId As Integer
			Get
		        Return Me._documentMetadataId
			End Get
			Set(ByVal value As Integer)
		        Me._documentMetadataId = value
			End Set
		End Property
		
		Private _created As Date? 
		Public Overridable Property Created As Date?
			Get
		        Return Me._created
			End Get
			Set(ByVal value As Date?)
		        Me._created = value
			End Set
		End Property
		
		Private _author As String 
		Public Overridable Property Author As String
			Get
		        Return Me._author
			End Get
			Set(ByVal value As String)
		        Me._author = value
			End Set
		End Property
		
		Private _category As String 
		Public Overridable Property Category As String
			Get
		        Return Me._category
			End Get
			Set(ByVal value As String)
		        Me._category = value
			End Set
		End Property
		
		Private _size As Double? 
		Public Overridable Property Size As Double?
			Get
		        Return Me._size
			End Get
			Set(ByVal value As Double?)
		        Me._size = value
			End Set
		End Property
		
		Private _tag As String 
		Public Overridable Property Tag As String
			Get
		        Return Me._tag
			End Get
			Set(ByVal value As String)
		        Me._tag = value
			End Set
		End Property
		
		Private _projects As IList(Of Project)  = new List(Of Project)
		Public Overridable ReadOnly Property Projects As IList(Of Project)
			Get
		        Return Me._projects
			End Get
		End Property
		
		Private _document As Document 
		Public Overridable Property Document As Document
			Get
		        Return Me._document
			End Get
			Set(ByVal value As Document)
		        Me._document = value
			End Set
		End Property
		
	End Class
End Namespace
