'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by the ClassGenerator.ttinclude code generation file.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports Telerik.OpenAccess.Data.Common
Imports Telerik.OpenAccess.Metadata.Fluent
Imports Telerik.OpenAccess.Metadata.Fluent.Advanced
Imports ContextApi.Model

Namespace ContextApi.Model	
	Public Partial Class Document
		Private _documentId As Integer 
		Public Overridable Property DocumentId As Integer
			Get
		        Return Me._documentId
			End Get
			Set(ByVal value As Integer)
		        Me._documentId = value
			End Set
		End Property
		
		Private _data As Byte() 
		Public Overridable Property Data As Byte()
			Get
		        Return Me._data
			End Get
			Set(ByVal value As Byte())
		        Me._data = value
			End Set
		End Property
		
		Private _checksum As Integer 
		Public Overridable Property Checksum As Integer
			Get
		        Return Me._checksum
			End Get
			Set(ByVal value As Integer)
		        Me._checksum = value
			End Set
		End Property
		
		Private _concurencyVersion As Integer 
		Public Overridable Property ConcurencyVersion As Integer
			Get
		        Return Me._concurencyVersion
			End Get
			Set(ByVal value As Integer)
		        Me._concurencyVersion = value
			End Set
		End Property
		
		Private _documentMetadatum As DocumentMetadata 
		Public Overridable Property DocumentMetadatum As DocumentMetadata
			Get
		        Return Me._documentMetadatum
			End Get
			Set(ByVal value As DocumentMetadata)
		        Me._documentMetadatum = value
			End Set
		End Property
		
	End Class
End Namespace
