'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by the ClassGenerator.ttinclude code generation file.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports Telerik.OpenAccess.Data.Common
Imports Telerik.OpenAccess.Metadata.Fluent
Imports Telerik.OpenAccess.Metadata.Fluent.Advanced
Imports ContextApi.Model

Namespace ContextApi.Model	
	Public Partial Class Employee
		Private _title As String 
		Public Overridable Property Title As String
			Get
		        Return Me._title
			End Get
			Set(ByVal value As String)
		        Me._title = value
			End Set
		End Property
		
		Private _projectId As Integer? 
		Public Overridable Property ProjectId As Integer?
			Get
		        Return Me._projectId
			End Get
			Set(ByVal value As Integer?)
		        Me._projectId = value
			End Set
		End Property
		
		Private _lastName As String 
		Public Overridable Property LastName As String
			Get
		        Return Me._lastName
			End Get
			Set(ByVal value As String)
		        Me._lastName = value
			End Set
		End Property
		
		Private _firstName As String 
		Public Overridable Property FirstName As String
			Get
		        Return Me._firstName
			End Get
			Set(ByVal value As String)
		        Me._firstName = value
			End Set
		End Property
		
		Private _employeeId As Integer 
		Public Overridable Property EmployeeId As Integer
			Get
		        Return Me._employeeId
			End Get
			Set(ByVal value As Integer)
		        Me._employeeId = value
			End Set
		End Property
		
		Private _reportToId As Integer? 
		Public Overridable Property ReportToId As Integer?
			Get
		        Return Me._reportToId
			End Get
			Set(ByVal value As Integer?)
		        Me._reportToId = value
			End Set
		End Property
		
		Private _department As String 
		Public Overridable Property Department As String
			Get
		        Return Me._department
			End Get
			Set(ByVal value As String)
		        Me._department = value
			End Set
		End Property
		
		Private _addres As String 
		Public Overridable Property Addres As String
			Get
		        Return Me._addres
			End Get
			Set(ByVal value As String)
		        Me._addres = value
			End Set
		End Property
		
		Private _employee1 As Employee 
		Public Overridable Property Supervisor As Employee
			Get
		        Return Me._employee1
			End Get
			Set(ByVal value As Employee)
		        Me._employee1 = value
			End Set
		End Property
		
		Private _taskAssignments As IList(Of TaskAssignment)  = new List(Of TaskAssignment)
		Public Overridable ReadOnly Property TaskAssignments As IList(Of TaskAssignment)
			Get
		        Return Me._taskAssignments
			End Get
		End Property
		
		Private _employees1 As IList(Of Employee)  = new List(Of Employee)
		Public Overridable ReadOnly Property Employees As IList(Of Employee)
			Get
		        Return Me._employees1
			End Get
		End Property
		
		Private _monthlyReports As IList(Of MonthlyReport)  = new List(Of MonthlyReport)
		Public Overridable ReadOnly Property MonthlyReports As IList(Of MonthlyReport)
			Get
		        Return Me._monthlyReports
			End Get
		End Property
		
		Private _dailyReports As IList(Of DailyReport)  = new List(Of DailyReport)
		Public Overridable ReadOnly Property DailyReports As IList(Of DailyReport)
			Get
		        Return Me._dailyReports
			End Get
		End Property
		
		Private _projects As IList(Of Project)  = new List(Of Project)
		Public Overridable ReadOnly Property Projects As IList(Of Project)
			Get
		        Return Me._projects
			End Get
		End Property
		
	End Class
End Namespace
