'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by the ContextGenerator.ttinclude code generation file.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports Telerik.OpenAccess.Data.Common
Imports Telerik.OpenAccess.Metadata.Fluent
Imports Telerik.OpenAccess.Metadata.Fluent.Advanced
Imports ContextApi.Model

Namespace ContextApi.Model	
	Public Partial Class EntitiesModel
		Inherits OpenAccessContext
		Implements IEntitiesModelUnitOfWork
		Private Shared connectionStringName As String = "ProjectManagementConnection"
		
		Private Shared backend As BackendConfiguration = GetBackendConfiguration()
				
		Private Shared metadataSource As MetadataSource = New EntitiesModelFluentMetadataSource()
		
		Public Sub New()
			MyBase.New(connectionStringName, backend, metadataSource)
		End Sub
			
		Public Sub New(ByVal connection As String)
			MyBase.New(connection, backend, metadataSource)
		End Sub
			
		Public Sub New(ByVal backendConfiguration As BackendConfiguration)
			MyBase.New(connectionStringName, backendConfiguration, metadataSource)
		End Sub
				
		Public Sub New(ByVal connection As String, ByVal metadataSource As MetadataSource)
			MyBase.New(connection, backend, metadataSource)
		End Sub
				
		Public Sub New(ByVal connection As String, ByVal backendConfiguration As BackendConfiguration, ByVal metadataSource As MetadataSource)
			MyBase.New(connection, backendConfiguration, metadataSource)
		End Sub
			
		Public ReadOnly Property Tasks() As  IQueryable(Of Task) Implements IEntitiesModelUnitOfWork.Tasks
		    Get
				Return Me.GetAll(Of Task)()
		    End Get
		End Property
		
		Public ReadOnly Property TaskAssignments() As  IQueryable(Of TaskAssignment) Implements IEntitiesModelUnitOfWork.TaskAssignments
		    Get
				Return Me.GetAll(Of TaskAssignment)()
		    End Get
		End Property
		
		Public ReadOnly Property Projects() As  IQueryable(Of Project) Implements IEntitiesModelUnitOfWork.Projects
		    Get
				Return Me.GetAll(Of Project)()
		    End Get
		End Property
		
		Public ReadOnly Property Employees() As  IQueryable(Of Employee) Implements IEntitiesModelUnitOfWork.Employees
		    Get
				Return Me.GetAll(Of Employee)()
		    End Get
		End Property
		
		Public ReadOnly Property DocumentMetadatum() As  IQueryable(Of DocumentMetadata) Implements IEntitiesModelUnitOfWork.DocumentMetadatum
		    Get
				Return Me.GetAll(Of DocumentMetadata)()
		    End Get
		End Property
		
		Public ReadOnly Property Documents() As  IQueryable(Of Document) Implements IEntitiesModelUnitOfWork.Documents
		    Get
				Return Me.GetAll(Of Document)()
		    End Get
		End Property
		
		Public ReadOnly Property Managers() As  IQueryable(Of Manager) Implements IEntitiesModelUnitOfWork.Managers
		    Get
				Return Me.GetAll(Of Manager)()
		    End Get
		End Property
		
		Public ReadOnly Property Reports1() As  IQueryable(Of Report) Implements IEntitiesModelUnitOfWork.Reports1
		    Get
				Return Me.GetAll(Of Report)()
		    End Get
		End Property
		
		Public ReadOnly Property MonthlyReports() As  IQueryable(Of MonthlyReport) Implements IEntitiesModelUnitOfWork.MonthlyReports
		    Get
				Return Me.GetAll(Of MonthlyReport)()
		    End Get
		End Property
		
		Public ReadOnly Property DailyReports() As  IQueryable(Of DailyReport) Implements IEntitiesModelUnitOfWork.DailyReports
		    Get
				Return Me.GetAll(Of DailyReport)()
		    End Get
		End Property
		
		Public ReadOnly Property NewItems() As  IQueryable(Of NewItem) Implements IEntitiesModelUnitOfWork.NewItems
		    Get
				Return Me.GetAll(Of NewItem)()
		    End Get
		End Property
		
		Public ReadOnly Property Bugs() As  IQueryable(Of Bug) Implements IEntitiesModelUnitOfWork.Bugs
		    Get
				Return Me.GetAll(Of Bug)()
		    End Get
		End Property
		
		Public Sub Reroute_Add(entity As Object) Implements IUnitOfWork.Add
			Me.Add(entity)
		End Sub
		
		Public Sub Reroute_ClearChanges() Implements IUnitOfWork.ClearChanges
			Me.ClearChanges()
		End Sub
		
		Public Sub Reroute_Delete(entity As Object) Implements IUnitOfWork.Delete
			Me.Delete(entity)
		End Sub
		
		Public Function Reroute_GetAll(Of T)() As IQueryable(Of T) Implements IUnitOfWork.GetAll
			Return Me.GetAll(Of T)()
		End Function
		
		Public Function Reroute_GetObjectByKey(Of T)(key As Telerik.OpenAccess.ObjectKey) As T Implements IUnitOfWork.GetObjectByKey
			Return CType(Me.GetObjectByKey(key), T)
		End Function
		
		Public Sub Reroute_SaveChanges() Implements IUnitOfWork.SaveChanges
			Me.SaveChanges()
		End Sub
		Public Shared Function GetBackendConfiguration() As BackendConfiguration
			Dim backend As BackendConfiguration = New BackendConfiguration()
			backend.Backend = "MsSql"
			backend.ProviderName = "System.Data.SqlClient"
			backend.Logging.MetricStoreSnapshotInterval = 0
			
			CustomizeBackendConfiguration(backend)
		
			Return backend
		End Function
		
		''' <summary>
		''' Allows you to customize the BackendConfiguration of EntitiesModel.
		''' </summary>
		''' <param name="config">The BackendConfiguration of EntitiesModel.</param>
		Private Shared Partial Sub CustomizeBackendConfiguration(ByRef config As BackendConfiguration)
		End Sub
		
	End Class
	
	Public Interface IEntitiesModelUnitOfWork
		Inherits IUnitOfWork
		ReadOnly Property Tasks() As IQueryable(Of Task)
		ReadOnly Property TaskAssignments() As IQueryable(Of TaskAssignment)
		ReadOnly Property Projects() As IQueryable(Of Project)
		ReadOnly Property Employees() As IQueryable(Of Employee)
		ReadOnly Property DocumentMetadatum() As IQueryable(Of DocumentMetadata)
		ReadOnly Property Documents() As IQueryable(Of Document)
		ReadOnly Property Managers() As IQueryable(Of Manager)
		ReadOnly Property Reports1() As IQueryable(Of Report)
		ReadOnly Property MonthlyReports() As IQueryable(Of MonthlyReport)
		ReadOnly Property DailyReports() As IQueryable(Of DailyReport)
		ReadOnly Property NewItems() As IQueryable(Of NewItem)
		ReadOnly Property Bugs() As IQueryable(Of Bug)
	End Interface
End Namespace
