'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by the ClassGenerator.ttinclude code generation file.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports Telerik.OpenAccess.Data.Common
Imports Telerik.OpenAccess.Metadata.Fluent
Imports Telerik.OpenAccess.Metadata.Fluent.Advanced
Imports ContextApi.Model

Namespace ContextApi.Model	
	Public Partial Class Manager
		Inherits Employee
		Private _managedDepartment As String 
		Public Overridable Property ManagedDepartment As String
			Get
		        Return Me._managedDepartment
			End Get
			Set(ByVal value As String)
		        Me._managedDepartment = value
			End Set
		End Property
		
	End Class
End Namespace
