'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by the ClassGenerator.ttinclude code generation file.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports Telerik.OpenAccess.Data.Common
Imports Telerik.OpenAccess.Metadata.Fluent
Imports Telerik.OpenAccess.Metadata.Fluent.Advanced
Imports ContextApi.Model

Namespace ContextApi.Model	
	Public Partial Class NewItem
		Inherits Task
		Private _startTime As Date 
		Public Overridable Property StartTime As Date
			Get
		        Return Me._startTime
			End Get
			Set(ByVal value As Date)
		        Me._startTime = value
			End Set
		End Property
		
		Private _readyFor As Date? 
		Public Overridable Property ReadyFor As Date?
			Get
		        Return Me._readyFor
			End Get
			Set(ByVal value As Date?)
		        Me._readyFor = value
			End Set
		End Property
		
	End Class
End Namespace
