'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by the ClassGenerator.ttinclude code generation file.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports Telerik.OpenAccess.Data.Common
Imports Telerik.OpenAccess.Metadata.Fluent
Imports Telerik.OpenAccess.Metadata.Fluent.Advanced

Namespace ContextApi.Model	
	Public Partial Class Report
		Protected _reportId As Integer 
		Public Overridable Property ReportId As Integer
			Get
		        Return Me._reportId
			End Get
			Set(ByVal value As Integer)
		        Me._reportId = value
			End Set
		End Property
		
		Protected _title As String 
		Public Overridable Property Title As String
			Get
		        Return Me._title
			End Get
			Set(ByVal value As String)
		        Me._title = value
			End Set
		End Property
		
		Protected _employeeId As Integer? 
		Public Overridable Property EmployeeId As Integer?
			Get
		        Return Me._employeeId
			End Get
			Set(ByVal value As Integer?)
		        Me._employeeId = value
			End Set
		End Property
		
		Protected _context As String 
		Public Overridable Property Context As String
			Get
		        Return Me._context
			End Get
			Set(ByVal value As String)
		        Me._context = value
			End Set
		End Property
		
	End Class
End Namespace
