'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by the ClassGenerator.ttinclude code generation file.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports Telerik.OpenAccess.Data.Common
Imports Telerik.OpenAccess.Metadata.Fluent
Imports Telerik.OpenAccess.Metadata.Fluent.Advanced
Imports ContextApi.Model

Namespace ContextApi.Model	
	Public Partial Class TaskAssignment
		Private _taskAssignmentId As Integer 
		Public Overridable Property TaskAssignmentId As Integer
			Get
		        Return Me._taskAssignmentId
			End Get
			Set(ByVal value As Integer)
		        Me._taskAssignmentId = value
			End Set
		End Property
		
		Private _taskId As Integer 
		Public Overridable Property TaskId As Integer
			Get
		        Return Me._taskId
			End Get
			Set(ByVal value As Integer)
		        Me._taskId = value
			End Set
		End Property
		
		Private _employeeId As Integer? 
		Public Overridable Property EmployeeId As Integer?
			Get
		        Return Me._employeeId
			End Get
			Set(ByVal value As Integer?)
		        Me._employeeId = value
			End Set
		End Property
		
		Private _workingHours As Integer? 
		Public Overridable Property WorkingHours As Integer?
			Get
		        Return Me._workingHours
			End Get
			Set(ByVal value As Integer?)
		        Me._workingHours = value
			End Set
		End Property
		
		Private _employee As Employee 
		Public Overridable Property Employee As Employee
			Get
		        Return Me._employee
			End Get
			Set(ByVal value As Employee)
		        Me._employee = value
			End Set
		End Property
		
		Private _task As Task 
		Public Overridable Property Task As Task
			Get
		        Return Me._task
			End Get
			Set(ByVal value As Task)
		        Me._task = value
			End Set
		End Property
		
	End Class
End Namespace
