'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by the ClassGenerator.ttinclude code generation file.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Data.Common
Imports System.Collections.Generic
Imports Telerik.OpenAccess
Imports Telerik.OpenAccess.Metadata
Imports Telerik.OpenAccess.Data.Common
Imports Telerik.OpenAccess.Metadata.Fluent
Imports Telerik.OpenAccess.Metadata.Fluent.Advanced
Imports ContextApi.Model

Namespace ContextApi.Model	
	Public Partial Class Task
		Private _title As String 
		Public Overridable Property Title As String
			Get
		        Return Me._title
			End Get
			Set(ByVal value As String)
		        Me._title = value
			End Set
		End Property
		
		Private _taskId As Integer 
		Public Overridable Property TaskId As Integer
			Get
		        Return Me._taskId
			End Get
			Set(ByVal value As Integer)
		        Me._taskId = value
			End Set
		End Property
		
		Private _projectId As Integer 
		Public Overridable Property ProjectId As Integer
			Get
		        Return Me._projectId
			End Get
			Set(ByVal value As Integer)
		        Me._projectId = value
			End Set
		End Property
		
		Private _status As String 
		Public Overridable Property Status As String
			Get
		        Return Me._status
			End Get
			Set(ByVal value As String)
		        Me._status = value
			End Set
		End Property
		
		Private _priority As Integer? 
		Public Overridable Property Priority As Integer?
			Get
		        Return Me._priority
			End Get
			Set(ByVal value As Integer?)
		        Me._priority = value
			End Set
		End Property
		
		Private _percentCompleted As Integer? 
		Public Overridable Property PercentCompleted As Integer?
			Get
		        Return Me._percentCompleted
			End Get
			Set(ByVal value As Integer?)
		        Me._percentCompleted = value
			End Set
		End Property
		
		Private _project As Project 
		Public Overridable Property Project As Project
			Get
		        Return Me._project
			End Get
			Set(ByVal value As Project)
		        Me._project = value
			End Set
		End Property
		
		Private _taskAssignments As IList(Of TaskAssignment)  = new List(Of TaskAssignment)
		Public Overridable ReadOnly Property TaskAssignments As IList(Of TaskAssignment)
			Get
		        Return Me._taskAssignments
			End Get
		End Property
		
	End Class
End Namespace
